const words = [
  { chinese: "巴士", english: "bus", image: "https://imgbin.com/png/9WEqhE9B/bus-minecraft-mods-railroad-car-png" },
  { chinese: "地鐵", english: "subway", image: "https://icons8.com/icon/1tKAGgaF-URc/minecraft-rail" },
  { chinese: "的士", english: "taxi", image: "https://www.cleanpng.com/png-minecraft-car-png-img-download-63662.html" },
  { chinese: "單車", english: "bicycle", image: "https://icons8.com/icon/1tKAGgaF-URc/minecraft-rail" },
  { chinese: "汽車", english: "car", image: "https://www.cleanpng.com/png-minecraft-car-png-img-download-63662.html" },
  { chinese: "校車", english: "school bus", image: "https://favpng.com/png_view/minecraft-minecraft-mods-omsi-the-bus-simulator-minecraft-mods-png/5ecKSsBn" },
  { chinese: "船", english: "ship", image: "https://icons8.com/icon/1tKAGgaF-URc/minecraft-boat" },
  { chinese: "火車", english: "train", image: "https://icons8.com/icon/1tKAGgaF-URc/minecraft-rail" },
  { chinese: "飛機", english: "airplane", image: "https://icons8.com/icon/dCZE9hMlig7j/minecraft-paper" }, 
  { chinese: "筆", english: "pen", image: "https://icons8.com/icon/JxsjajuoAosA/minecraft-book" }, 
  { chinese: "鉛筆", english: "pencil", image: "https://icons8.com/icon/JxsjajuoAosA/minecraft-book" }, 
  { chinese: "書包", english: "school bag", image: "https://icons8.com/icon/2JmdnbqBk8a0/minecraft-chest" }, 
  { chinese: "教室", english: "classroom", image: "https://stablediffusionweb.com/image/16503221-logo-for-minecraft-school-smp" }, 
  { chinese: "黑板", english: "blackboard", image: "https://icons8.com/icon/EBHDwIOih9FO/minecraft-sign" }, 
  { chinese: "桌子", english: "table", image: "https://icons8.com/icon/8Eu1S0vDsus4/minecraft-table" }, 
  { chinese: "椅子", english: "chair", image: "https://icons8.com/icon/2vngPZDl7WoB/minecraft-door" }, 
  { chinese: "水樽", english: "water bottle", image: "https://icons8.com/icon/2yocnRmPrGhA/potion-minecraft" }, 
  { chinese: "午餐", english: "lunch", image: "https://icons8.com/icon/HZWg1RBlaV4s/porkchop-minecraft" }, 
  { chinese: "飯盒", english: "lunch box", image: "https://icons8.com/icon/2JmdnbqBk8a0/minecraft-chest" }, 
  { chinese: "水果", english: "fruit", image: "https://www.freepik.com/icons/minecraft-melon" }, 
  { chinese: "蘋果", english: "apple", image: "https://icons8.com/icon/HZWg1RBlaV4s/minecraft-apple" }, 
  { chinese: "香蕉", english: "banana", image: "https://icons8.com/icon/2yocnRmPrGhA/potion-minecraft" },
  { chinese: "橙", english: "orange", image: "https://icons8.com/icon/HZWg1RBlaV4s/minecraft-apple" },
  { chinese: "西瓜", english: "watermelon", image: "https://icons8.com/icon/2yocnRmPrGhA/minecraft-melon" }, 
  { chinese: "牛奶", english: "milk", image: "https://icons8.com/icon/gxzZOAog7gR8/minecraft-bucket" }, 
  { chinese: "麵包", english: "bread", image: "https://icons8.com/icon/2yocnRmPrGhA/minecraft-bread" }, 
  { chinese: "蛋", english: "egg", image: "https://icons8.com/icon/2yocnRmPrGhA/minecraft-egg" }, 
  { chinese: "湯", english: "soup", image: "https://icons8.com/icon/ghkNLE8pOruV/minecraft-bowl" }, 
  { chinese: "糖", english: "candy", image: "https://icons8.com/icon/HZWg1RBlaV4s/minecraft-apple" },
  { chinese: "朱古力", english: "chocolate", image: "https://icons8.com/icon/HZWg1RBlaV4s/minecraft-apple" },
  { chinese: "雪糕", english: "ice cream", image: "https://icons8.com/icon/gxzZOAog7gR8/minecraft-bucket" },
  { chinese: "魚", english: "fish", image: "https://icons8.com/icon/HZWg1RBlaV4s/minecraft-fish" }, 
  { chinese: "狗", english: "dog", image: "https://icons8.com/icon/esz9D3eojfhl/wolf-minecraft" }, 
  { chinese: "貓", english: "cat", image: "https://icons8.com/icon/afwqNpXZLWWy/cat-minecraft-pointer" }, 
  { chinese: "馬", english: "horse", image: "https://icons8.com/icon/BUUwkj4Mn8yh/horse-minecraft" }, 
  { chinese: "兔", english: "rabbit", image: "https://icons8.com/icon/qXw2LRN9WkA6/rabbit-minecraft" }, 
  { chinese: "鳥", english: "bird", image: "https://icons8.com/icon/BUUwkj4Mn8yh/parrot-minecraft" }, 
  { chinese: "太陽", english: "sun", image: "https://icons8.com/icon/8O2Q7rZPoo2k/time-minecraft" }, 
  { chinese: "月亮", english: "moon", image: "https://icons8.com/icon/8O2Q7rZPoo2k/time-minecraft" }, 
  { chinese: "星星", english: "star", image: "https://icons8.com/icon/8O2Q7rZPoo2k/time-minecraft" }, 
  { chinese: "花", english: "flower", image: "https://icons8.com/icon/HZWg1RBlaV4s/minecraft-flower" }, 
  { chinese: "樹", english: "tree", image: "https://icons8.com/icon/2yocnRmPrGhA/minecraft-tree" }, 
  { chinese: "葉", english: "leaf", image: "https://icons8.com/icon/HZWg1RBlaV4s/minecraft-flower" },
  { chinese: "草", english: "grass", image: "https://icons8.com/icon/HZWg1RBlaV4s/minecraft-flower" }, 
  { chinese: "山", english: "mountain", image: "https://icons8.com/icon/Qyh9Bt4b6KMr/minecraft-mountain" }, 
  { chinese: "河", english: "river", image: "https://icons8.com/icon/HZWg1RBlaV4s/minecraft-fish" }, 
  { chinese: "海", english: "sea", image: "https://icons8.com/icon/HZWg1RBlaV4s/minecraft-fish" }, 
  { chinese: "雲", english: "cloud", image: "https://icons8.com/icon/8O2Q7rZPoo2k/time-minecraft" }, 
  { chinese: "雨", english: "rain", image: "https://icons8.com/icon/8O2Q7rZPoo2k/time-minecraft" }, 
  { chinese: "雪", english: "snow", image: "https://icons8.com/icon/gxzZOAog7gR8/minecraft-bucket" }
];
