const words = [
  { chinese: "巴士", english: "bus", image: "https://openmoji.org/data/color/svg/1F68C.svg" },
  { chinese: "地鐵", english: "subway", image: "https://openmoji.org/data/color/svg/1F687.svg" },
  { chinese: "的士", english: "taxi", image: "https://openmoji.org/data/color/svg/1F695.svg" },
  { chinese: "單車", english: "bicycle", image: "https://openmoji.org/data/color/svg/1F6B2.svg" },
  { chinese: "汽車", english: "car", image: "https://openmoji.org/data/color/svg/1F697.svg" },
  { chinese: "校車", english: "school bus", image: "https://openmoji.org/data/color/svg/1F68C.svg" },
  { chinese: "船", english: "ship", image: "https://openmoji.org/data/color/svg/1F6A2.svg" },
  { chinese: "火車", english: "train", image: "https://openmoji.org/data/color/svg/1F686.svg" },
  { chinese: "飛機", english: "airplane", image: "https://openmoji.org/data/color/svg/2708.svg" },
  { chinese: "筆", english: "pen", image: "https://openmoji.org/data/color/svg/270F.svg" },
  { chinese: "鉛筆", english: "pencil", image: "https://openmoji.org/data/color/svg/270F.svg" },
  { chinese: "書包", english: "school bag", image: "https://openmoji.org/data/color/svg/1F392.svg" },
  { chinese: "教室", english: "classroom", image: "https://openmoji.org/data/color/svg/1F3EB.svg" },
  { chinese: "黑板", english: "blackboard", image: "https://openmoji.org/data/color/svg/1F5A5.svg" },
  { chinese: "桌子", english: "table", image: "https://openmoji.org/data/color/svg/1F4C4.svg" },
  { chinese: "椅子", english: "chair", image: "https://openmoji.org/data/color/svg/1F4BA.svg" },
  { chinese: "水樽", english: "water bottle", image: "https://openmoji.org/data/color/svg/1F9EA.svg" },
  { chinese: "午餐", english: "lunch", image: "https://openmoji.org/data/color/svg/1F37D.svg" },
  { chinese: "飯盒", english: "lunch box", image: "https://openmoji.org/data/color/svg/1F37E.svg" },
  { chinese: "水果", english: "fruit", image: "https://openmoji.org/data/color/svg/1F34E.svg" },
  { chinese: "蘋果", english: "apple", image: "https://openmoji.org/data/color/svg/1F34E.svg" },
  { chinese: "香蕉", english: "banana", image: "https://openmoji.org/data/color/svg/1F34C.svg" },
  { chinese: "橙", english: "orange", image: "https://openmoji.org/data/color/svg/1F34A.svg" },
  { chinese: "西瓜", english: "watermelon", image: "https://openmoji.org/data/color/svg/1F349.svg" },
  { chinese: "牛奶", english: "milk", image: "https://openmoji.org/data/color/svg/1F95B.svg" },
  { chinese: "麵包", english: "bread", image: "https://openmoji.org/data/color/svg/1F35E.svg" },
  { chinese: "蛋", english: "egg", image: "https://openmoji.org/data/color/svg/1F95A.svg" },
  { chinese: "湯", english: "soup", image: "https://openmoji.org/data/color/svg/1F35C.svg" },
  { chinese: "糖", english: "candy", image: "https://openmoji.org/data/color/svg/1F36C.svg" },
  { chinese: "朱古力", english: "chocolate", image: "https://openmoji.org/data/color/svg/1F36B.svg" },
  { chinese: "雪糕", english: "ice cream", image: "https://openmoji.org/data/color/svg/1F366.svg" },
  { chinese: "魚", english: "fish", image: "https://openmoji.org/data/color/svg/1F41F.svg" },
  { chinese: "狗", english: "dog", image: "https://openmoji.org/data/color/svg/1F436.svg" },
  { chinese: "貓", english: "cat", image: "https://openmoji.org/data/color/svg/1F431.svg" },
  { chinese: "馬", english: "horse", image: "https://openmoji.org/data/color/svg/1F40E.svg" },
  { chinese: "兔", english: "rabbit", image: "https://openmoji.org/data/color/svg/1F430.svg" },
  { chinese: "鳥", english: "bird", image: "https://openmoji.org/data/color/svg/1F426.svg" },
  { chinese: "太陽", english: "sun", image: "https://openmoji.org/data/color/svg/2600.svg" },
  { chinese: "月亮", english: "moon", image: "https://openmoji.org/data/color/svg/1F319.svg" },
  { chinese: "星星", english: "star", image: "https://openmoji.org/data/color/svg/2B50.svg" },
  { chinese: "花", english: "flower", image: "https://openmoji.org/data/color/svg/1F33C.svg" },
  { chinese: "樹", english: "tree", image: "https://openmoji.org/data/color/svg/1F333.svg" },
  { chinese: "葉", english: "leaf", image: "https://openmoji.org/data/color/svg/1F342.svg" },
  { chinese: "草", english: "grass", image: "https://openmoji.org/data/color/svg/1F33F.svg" },
  { chinese: "山", english: "mountain", image: "https://openmoji.org/data/color/svg/26F0.svg" },
  { chinese: "河", english: "river", image: "https://openmoji.org/data/color/svg/1F30A.svg" },
  { chinese: "海", english: "sea", image: "https://openmoji.org/data/color/svg/1F30A.svg" },
  { chinese: "雲", english: "cloud", image: "https://openmoji.org/data/color/svg/2601.svg" },
  { chinese: "雨", english: "rain", image: "https://openmoji.org/data/color/svg/1F327.svg" },
  { chinese: "雪", english: "snow", image: "https://openmoji.org/data/color/svg/2744.svg" }
];
